[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageContrastAdjustment = "f332f351-ec65-5f6a-b3d1-319c6670881a"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
